# Auto-generated by IDE. All changes by user will be lost!
# Created at 1/20/13 5:13 PM

BASEDIR = $$_PRO_FILE_PWD_

INCLUDEPATH +=  \
    $$BASEDIR/src/oauth \
    $$BASEDIR/src

SOURCES +=  \
    $$BASEDIR/src/AbstractObjectBase.cpp \
    $$BASEDIR/src/ApiResponse.cpp \
    $$BASEDIR/src/ApiResponseObjectFactory.cpp \
    $$BASEDIR/src/HomeLayout.cpp \
    $$BASEDIR/src/LoginLayout.cpp \
    $$BASEDIR/src/RequestEnvelope.cpp \
    $$BASEDIR/src/ResponseMeta.cpp \
    $$BASEDIR/src/Tweet.cpp \
    $$BASEDIR/src/Twitter.cpp \
    $$BASEDIR/src/TwitterApi.cpp \
    $$BASEDIR/src/User.cpp \
    $$BASEDIR/src/oauth/kqoauth2request.cpp \
    $$BASEDIR/src/oauth/kqoauthauthreplyserver.cpp \
    $$BASEDIR/src/oauth/kqoauthmanager.cpp \
    $$BASEDIR/src/oauth/kqoauthrequest.cpp \
    $$BASEDIR/src/oauth/kqoauthrequest_1.cpp \
    $$BASEDIR/src/oauth/kqoauthrequest_xauth.cpp \
    $$BASEDIR/src/oauth/kqoauthutils.cpp \
    $$BASEDIR/src/twittermain.cpp

HEADERS +=  \
    $$BASEDIR/src/AbstractObjectBase.h \
    $$BASEDIR/src/ApiResponse.h \
    $$BASEDIR/src/ApiResponseObjectFactory.h \
    $$BASEDIR/src/HomeLayout.h \
    $$BASEDIR/src/LoginLayout.h \
    $$BASEDIR/src/RequestEnvelope.h \
    $$BASEDIR/src/ResponseMeta.h \
    $$BASEDIR/src/Tweet.h \
    $$BASEDIR/src/Twitter.hpp \
    $$BASEDIR/src/TwitterApi.h \
    $$BASEDIR/src/User.h \
    $$BASEDIR/src/oauth/kqoauth2request.h \
    $$BASEDIR/src/oauth/kqoauth2request_p.h \
    $$BASEDIR/src/oauth/kqoauthauthreplyserver.h \
    $$BASEDIR/src/oauth/kqoauthauthreplyserver_p.h \
    $$BASEDIR/src/oauth/kqoauthglobals.h \
    $$BASEDIR/src/oauth/kqoauthmanager.h \
    $$BASEDIR/src/oauth/kqoauthmanager_p.h \
    $$BASEDIR/src/oauth/kqoauthrequest.h \
    $$BASEDIR/src/oauth/kqoauthrequest_1.h \
    $$BASEDIR/src/oauth/kqoauthrequest_p.h \
    $$BASEDIR/src/oauth/kqoauthrequest_xauth.h \
    $$BASEDIR/src/oauth/kqoauthrequest_xauth_p.h \
    $$BASEDIR/src/oauth/kqoauthutils.h

CONFIG += precompile_header
PRECOMPILED_HEADER = $$BASEDIR/precompiled.h

lupdate_inclusion {
    SOURCES += \
        $$BASEDIR/../assets/*.qml
}

TRANSLATIONS = \
    $${TARGET}.ts

